[package]
name = "_operators_0_constant_3_value"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "bde88b6" } 
[lib]
sierra-text = true