[package]
name = "node__operators_0_biases_4"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "13f039f" } 
[lib]
sierra-text = true